---
name: bosh-101-classroom

releases:
- name: bosh
  version: "268.1.0"
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-268.1.0-ubuntu-xenial-97.22-20181005-190759-007936197-20181005190803.tgz
  sha1: ad96e6d3a0d7ed9dc52cc4e7c33690b8d099b9fe
- name: bosh-101
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 5
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

disk_pools:
- name: disks
  disk_size: 32_768

instance_groups:
- name: bosh
  instances: ((students_count))
  azs: [z1, z2, z3]
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: prepare_bosh101, release: bosh-101}
  vm_type: default
  stemcell: default
  persistent_disk_pool: large
  networks:
  - name: default
  properties:
    bosh101:
      stemcell_url: https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-97.28-warden-boshlite-ubuntu-xenial-go_agent.tgz
      release_url: https://github.com/mariash/learn-bosh-release
      release_branch: cloud-config
      bosh_cli_url: https://github.com/cloudfoundry/bosh-cli/releases/download/v5.3.1/bosh-cli-5.3.1-linux-amd64
    nats:
      address: 127.0.0.1
      user: nats
      password: ((nats_password))
      tls:
        ca: ((nats_server_tls.ca))
        client_ca:
          certificate: ((nats_ca.certificate))
          private_key: ((nats_ca.private_key))
        server:
          certificate: ((nats_server_tls.certificate))
          private_key: ((nats_server_tls.private_key))
        director:
          certificate: ((nats_clients_director_tls.certificate))
          private_key: ((nats_clients_director_tls.private_key))
        health_monitor:
          certificate: ((nats_clients_health_monitor_tls.certificate))
          private_key: ((nats_clients_health_monitor_tls.private_key))
    postgres: &db
      password: ((postgres_password))
    blobstore:
      address: 127.0.0.1
      port: 25250
      director:
        user: director
        password: ((blobstore_director_password))
      agent:
        user: agent
        password: ((blobstore_agent_password))
    director:
      address: 127.0.0.1
      name: bosh-101
      db: *db
      cpi_job: warden_cpi
      ignore_missing_gateway: true
      ssl:
        key: ((director_ssl.private_key))
        cert: ((director_ssl.certificate))
      user_management:
        provider: local
        local:
          users:
          - name: admin
            password: ((admin_password))
          - name: hm
            password: ((hm_password))
    hm:
      director_account:
        user: hm
        password: ((hm_password))
        ca_cert: ((director_ssl.ca))

variables:
- name: nats_ca
  type: certificate
  options:
    is_ca: true
    common_name: default.nats-ca.bosh-internal

- name: nats_server_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.nats.bosh-internal
    alternative_names: [((internal_ip))]
    extended_key_usage:
    - server_auth

- name: nats_clients_director_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.director.bosh-internal
    extended_key_usage:
    - client_auth

- name: nats_clients_health_monitor_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.hm.bosh-internal
    extended_key_usage:
    - client_auth

- name: blobstore_ca
  type: certificate
  options:
    is_ca: true
    common_name: default.blobstore-ca.bosh-internal

- name: blobstore_server_tls
  type: certificate
  options:
    ca: blobstore_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]
