#!/usr/bin/env bash

DEPLOYMENT_STATE_PATH=~/deployments/bosh-101

export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=`bosh int ${DEPLOYMENT_STATE_PATH}/creds.yml --path /admin_password`
export CREDHUB_CLIENT=credhub-admin
export CREDHUB_SECRET=`bosh int ${DEPLOYMENT_STATE_PATH}/creds.yml --path /credhub_admin_client_secret`
export CREDHUB_SERVER=https://10.0.0.6:8844
export CREDHUB_CA_CERT=`bosh int ${DEPLOYMENT_STATE_PATH}/creds.yml --path /credhub_ca/ca`

bosh alias-env bosh-101 -e 10.0.0.6 --ca-cert <(bosh int ${DEPLOYMENT_STATE_PATH}/creds.yml --path /director_ssl/ca)
