#!/usr/bin/env bash

set -e

if [ "$#" -ne 2 ]; then
    echo "Must provide gateway and destination IP addresses"
    exit 1
fi

GATEWAY_HOST=$1
DESTINATION_HOST=$2
DESTINATION_SSH_KEY=/home/jumpbox/.ssh/jumpbox.key

ssh -tt jumpbox@${GATEWAY_HOST} \
    ssh -i ${DESTINATION_SSH_KEY} -o StrictHostKeyChecking=no -tt jumpbox@${DESTINATION_HOST} /bin/bash
