#!/usr/bin/env bash

set -e
bosh -e bosh-101 update-cloud-config ~/workspace/bosh-deployment/gcp/cloud-config.yml \
    -o ./operations/gcp/cloud-config-bosh-101.yml \
    -v zone=us-east1-d \
    -v tags=[internal] \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v network=bosh \
    -v subnetwork=bosh-us-east1
